// Autogenerated from Pigeon (v10.1.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.fixit.fixit_webview.webview

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class PigeonRuntimeConfig (
  val initialUrl: String,
  val enablePooling: Boolean,
  val enableCache: Boolean,
  val enableBridge: Boolean,
  val javaScriptEnabled: Boolean,
  val domStorageEnabled: Boolean,
  val allowFileAccess: Boolean,
  val allowContentAccess: Boolean,
  val mediaPlaybackRequiresGesture: Boolean,
  val userAgent: String? = null,
  val navigationWhitelist: List<String?>,
  val navigationBlacklist: List<String?>,
  val acceptThirdPartyCookies: Boolean,
  val externalSchemes: List<String?>,
  val enableOffline: Boolean,
  val mixedContentMode: Long,
  val safeBrowsingEnabled: Boolean,
  val zoomEnabled: Boolean

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): PigeonRuntimeConfig {
      val initialUrl = list[0] as String
      val enablePooling = list[1] as Boolean
      val enableCache = list[2] as Boolean
      val enableBridge = list[3] as Boolean
      val javaScriptEnabled = list[4] as Boolean
      val domStorageEnabled = list[5] as Boolean
      val allowFileAccess = list[6] as Boolean
      val allowContentAccess = list[7] as Boolean
      val mediaPlaybackRequiresGesture = list[8] as Boolean
      val userAgent = list[9] as String?
      val navigationWhitelist = list[10] as List<String?>
      val navigationBlacklist = list[11] as List<String?>
      val acceptThirdPartyCookies = list[12] as Boolean
      val externalSchemes = list[13] as List<String?>
      val enableOffline = list[14] as Boolean
      val mixedContentMode = list[15].let { if (it is Int) it.toLong() else it as Long }
      val safeBrowsingEnabled = list[16] as Boolean
      val zoomEnabled = list[17] as Boolean
      return PigeonRuntimeConfig(initialUrl, enablePooling, enableCache, enableBridge, javaScriptEnabled, domStorageEnabled, allowFileAccess, allowContentAccess, mediaPlaybackRequiresGesture, userAgent, navigationWhitelist, navigationBlacklist, acceptThirdPartyCookies, externalSchemes, enableOffline, mixedContentMode, safeBrowsingEnabled, zoomEnabled)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      initialUrl,
      enablePooling,
      enableCache,
      enableBridge,
      javaScriptEnabled,
      domStorageEnabled,
      allowFileAccess,
      allowContentAccess,
      mediaPlaybackRequiresGesture,
      userAgent,
      navigationWhitelist,
      navigationBlacklist,
      acceptThirdPartyCookies,
      externalSchemes,
      enableOffline,
      mixedContentMode,
      safeBrowsingEnabled,
      zoomEnabled,
    )
  }
}

@Suppress("UNCHECKED_CAST")
private object FixitWebViewHostApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PigeonRuntimeConfig.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PigeonRuntimeConfig -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface FixitWebViewHostApi {
  fun create(viewId: Long, config: PigeonRuntimeConfig)
  fun loadUrl(viewId: Long, url: String)
  fun loadUrlWithHeaders(viewId: Long, url: String, headers: Map<String?, String?>?, method: String?, body: String?)
  fun loadHtmlString(viewId: Long, html: String, baseUrl: String?)
  fun stopLoading(viewId: Long)
  fun getTitle(viewId: Long): String?
  fun goBack(viewId: Long)
  fun goForward(viewId: Long)
  fun reload(viewId: Long)
  fun clearCache(viewId: Long)
  fun clearCookies()
  fun setCookie(url: String, key: String, value: String)
  fun getCookies(url: String, callback: (Result<List<String?>>) -> Unit)
  fun httpAuthResponse(viewId: Long, requestId: Long, username: String, password: String)
  fun cancelHttpAuth(viewId: Long, requestId: Long)
  fun updateSecurityConfig(viewId: Long, mixedContentMode: Long?, safeBrowsingEnabled: Boolean?, zoomEnabled: Boolean?)
  fun evaluateJavascript(viewId: Long, javascript: String)
  fun runJavascriptReturningResult(viewId: Long, javascript: String, callback: (Result<String?>) -> Unit)
  fun postBridgeMessage(viewId: Long, message: String)
  fun dispose(viewId: Long)

  companion object {
    /** The codec used by FixitWebViewHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      FixitWebViewHostApiCodec
    }
    /** Sets up an instance of `FixitWebViewHostApi` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: FixitWebViewHostApi?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.create", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            val configArg = args[1] as PigeonRuntimeConfig
            var wrapped: List<Any?>
            try {
              api.create(viewIdArg, configArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.loadUrl", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            val urlArg = args[1] as String
            var wrapped: List<Any?>
            try {
              api.loadUrl(viewIdArg, urlArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.loadUrlWithHeaders", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            val urlArg = args[1] as String
            val headersArg = args[2] as Map<String?, String?>?
            val methodArg = args[3] as String?
            val bodyArg = args[4] as String?
            var wrapped: List<Any?>
            try {
              api.loadUrlWithHeaders(viewIdArg, urlArg, headersArg, methodArg, bodyArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.loadHtmlString", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            val htmlArg = args[1] as String
            val baseUrlArg = args[2] as String?
            var wrapped: List<Any?>
            try {
              api.loadHtmlString(viewIdArg, htmlArg, baseUrlArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.stopLoading", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            var wrapped: List<Any?>
            try {
              api.stopLoading(viewIdArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.getTitle", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.getTitle(viewIdArg))
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.goBack", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            var wrapped: List<Any?>
            try {
              api.goBack(viewIdArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.goForward", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            var wrapped: List<Any?>
            try {
              api.goForward(viewIdArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.reload", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            var wrapped: List<Any?>
            try {
              api.reload(viewIdArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.clearCache", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            var wrapped: List<Any?>
            try {
              api.clearCache(viewIdArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.clearCookies", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              api.clearCookies()
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.setCookie", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            val keyArg = args[1] as String
            val valueArg = args[2] as String
            var wrapped: List<Any?>
            try {
              api.setCookie(urlArg, keyArg, valueArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.getCookies", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            api.getCookies(urlArg) { result: Result<List<String?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.httpAuthResponse", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            val requestIdArg = args[1].let { if (it is Int) it.toLong() else it as Long }
            val usernameArg = args[2] as String
            val passwordArg = args[3] as String
            var wrapped: List<Any?>
            try {
              api.httpAuthResponse(viewIdArg, requestIdArg, usernameArg, passwordArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.cancelHttpAuth", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            val requestIdArg = args[1].let { if (it is Int) it.toLong() else it as Long }
            var wrapped: List<Any?>
            try {
              api.cancelHttpAuth(viewIdArg, requestIdArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.updateSecurityConfig", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            val mixedContentModeArg = args[1].let { if (it is Int) it.toLong() else it as Long? }
            val safeBrowsingEnabledArg = args[2] as Boolean?
            val zoomEnabledArg = args[3] as Boolean?
            var wrapped: List<Any?>
            try {
              api.updateSecurityConfig(viewIdArg, mixedContentModeArg, safeBrowsingEnabledArg, zoomEnabledArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.evaluateJavascript", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            val javascriptArg = args[1] as String
            var wrapped: List<Any?>
            try {
              api.evaluateJavascript(viewIdArg, javascriptArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.runJavascriptReturningResult", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            val javascriptArg = args[1] as String
            api.runJavascriptReturningResult(viewIdArg, javascriptArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.postBridgeMessage", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            val messageArg = args[1] as String
            var wrapped: List<Any?>
            try {
              api.postBridgeMessage(viewIdArg, messageArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.dispose", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            var wrapped: List<Any?>
            try {
              api.dispose(viewIdArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
