// Autogenerated from Pigeon (v10.1.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct PigeonRuntimeConfig {
  var initialUrl: String
  var enablePooling: Bool
  var enableCache: Bool
  var enableBridge: Bool
  var javaScriptEnabled: Bool
  var domStorageEnabled: Bool
  var allowFileAccess: Bool
  var allowContentAccess: Bool
  var mediaPlaybackRequiresGesture: Bool
  var userAgent: String? = nil
  var navigationWhitelist: [String?]
  var navigationBlacklist: [String?]
  var acceptThirdPartyCookies: Bool
  var externalSchemes: [String?]
  var enableOffline: Bool
  var mixedContentMode: Int64
  var safeBrowsingEnabled: Bool
  var zoomEnabled: Bool

  static func fromList(_ list: [Any?]) -> PigeonRuntimeConfig? {
    let initialUrl = list[0] as! String
    let enablePooling = list[1] as! Bool
    let enableCache = list[2] as! Bool
    let enableBridge = list[3] as! Bool
    let javaScriptEnabled = list[4] as! Bool
    let domStorageEnabled = list[5] as! Bool
    let allowFileAccess = list[6] as! Bool
    let allowContentAccess = list[7] as! Bool
    let mediaPlaybackRequiresGesture = list[8] as! Bool
    let userAgent: String? = nilOrValue(list[9])
    let navigationWhitelist = list[10] as! [String?]
    let navigationBlacklist = list[11] as! [String?]
    let acceptThirdPartyCookies = list[12] as! Bool
    let externalSchemes = list[13] as! [String?]
    let enableOffline = list[14] as! Bool
    let mixedContentMode = list[15] is Int64 ? list[15] as! Int64 : Int64(list[15] as! Int32)
    let safeBrowsingEnabled = list[16] as! Bool
    let zoomEnabled = list[17] as! Bool

    return PigeonRuntimeConfig(
      initialUrl: initialUrl,
      enablePooling: enablePooling,
      enableCache: enableCache,
      enableBridge: enableBridge,
      javaScriptEnabled: javaScriptEnabled,
      domStorageEnabled: domStorageEnabled,
      allowFileAccess: allowFileAccess,
      allowContentAccess: allowContentAccess,
      mediaPlaybackRequiresGesture: mediaPlaybackRequiresGesture,
      userAgent: userAgent,
      navigationWhitelist: navigationWhitelist,
      navigationBlacklist: navigationBlacklist,
      acceptThirdPartyCookies: acceptThirdPartyCookies,
      externalSchemes: externalSchemes,
      enableOffline: enableOffline,
      mixedContentMode: mixedContentMode,
      safeBrowsingEnabled: safeBrowsingEnabled,
      zoomEnabled: zoomEnabled
    )
  }
  func toList() -> [Any?] {
    return [
      initialUrl,
      enablePooling,
      enableCache,
      enableBridge,
      javaScriptEnabled,
      domStorageEnabled,
      allowFileAccess,
      allowContentAccess,
      mediaPlaybackRequiresGesture,
      userAgent,
      navigationWhitelist,
      navigationBlacklist,
      acceptThirdPartyCookies,
      externalSchemes,
      enableOffline,
      mixedContentMode,
      safeBrowsingEnabled,
      zoomEnabled,
    ]
  }
}

private class FixitWebViewHostApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
      case 128:
        return PigeonRuntimeConfig.fromList(self.readValue() as! [Any?])
      default:
        return super.readValue(ofType: type)
    }
  }
}

private class FixitWebViewHostApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PigeonRuntimeConfig {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class FixitWebViewHostApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return FixitWebViewHostApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return FixitWebViewHostApiCodecWriter(data: data)
  }
}

class FixitWebViewHostApiCodec: FlutterStandardMessageCodec {
  static let shared = FixitWebViewHostApiCodec(readerWriter: FixitWebViewHostApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FixitWebViewHostApi {
  func create(viewId: Int64, config: PigeonRuntimeConfig) throws
  func loadUrl(viewId: Int64, url: String) throws
  func loadUrlWithHeaders(viewId: Int64, url: String, headers: [String?: String?]?, method: String?, body: String?) throws
  func loadHtmlString(viewId: Int64, html: String, baseUrl: String?) throws
  func stopLoading(viewId: Int64) throws
  func getTitle(viewId: Int64) throws -> String?
  func goBack(viewId: Int64) throws
  func goForward(viewId: Int64) throws
  func reload(viewId: Int64) throws
  func clearCache(viewId: Int64) throws
  func clearCookies() throws
  func setCookie(url: String, key: String, value: String) throws
  func getCookies(url: String, completion: @escaping (Result<[String?], Error>) -> Void)
  func httpAuthResponse(viewId: Int64, requestId: Int64, username: String, password: String) throws
  func cancelHttpAuth(viewId: Int64, requestId: Int64) throws
  func updateSecurityConfig(viewId: Int64, mixedContentMode: Int64?, safeBrowsingEnabled: Bool?, zoomEnabled: Bool?) throws
  func evaluateJavascript(viewId: Int64, javascript: String) throws
  func runJavascriptReturningResult(viewId: Int64, javascript: String, completion: @escaping (Result<String?, Error>) -> Void)
  func postBridgeMessage(viewId: Int64, message: String) throws
  func dispose(viewId: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FixitWebViewHostApiSetup {
  /// The codec used by FixitWebViewHostApi.
  static var codec: FlutterStandardMessageCodec { FixitWebViewHostApiCodec.shared }
  /// Sets up an instance of `FixitWebViewHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FixitWebViewHostApi?) {
    let createChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.create", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        let configArg = args[1] as! PigeonRuntimeConfig
        do {
          try api.create(viewId: viewIdArg, config: configArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createChannel.setMessageHandler(nil)
    }
    let loadUrlChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.loadUrl", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadUrlChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        let urlArg = args[1] as! String
        do {
          try api.loadUrl(viewId: viewIdArg, url: urlArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      loadUrlChannel.setMessageHandler(nil)
    }
    let loadUrlWithHeadersChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.loadUrlWithHeaders", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadUrlWithHeadersChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        let urlArg = args[1] as! String
        let headersArg: [String?: String?]? = nilOrValue(args[2])
        let methodArg: String? = nilOrValue(args[3])
        let bodyArg: String? = nilOrValue(args[4])
        do {
          try api.loadUrlWithHeaders(viewId: viewIdArg, url: urlArg, headers: headersArg, method: methodArg, body: bodyArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      loadUrlWithHeadersChannel.setMessageHandler(nil)
    }
    let loadHtmlStringChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.loadHtmlString", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadHtmlStringChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        let htmlArg = args[1] as! String
        let baseUrlArg: String? = nilOrValue(args[2])
        do {
          try api.loadHtmlString(viewId: viewIdArg, html: htmlArg, baseUrl: baseUrlArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      loadHtmlStringChannel.setMessageHandler(nil)
    }
    let stopLoadingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.stopLoading", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopLoadingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        do {
          try api.stopLoading(viewId: viewIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopLoadingChannel.setMessageHandler(nil)
    }
    let getTitleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.getTitle", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getTitleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        do {
          let result = try api.getTitle(viewId: viewIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getTitleChannel.setMessageHandler(nil)
    }
    let goBackChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.goBack", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      goBackChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        do {
          try api.goBack(viewId: viewIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      goBackChannel.setMessageHandler(nil)
    }
    let goForwardChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.goForward", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      goForwardChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        do {
          try api.goForward(viewId: viewIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      goForwardChannel.setMessageHandler(nil)
    }
    let reloadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.reload", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      reloadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        do {
          try api.reload(viewId: viewIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      reloadChannel.setMessageHandler(nil)
    }
    let clearCacheChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.clearCache", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearCacheChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        do {
          try api.clearCache(viewId: viewIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearCacheChannel.setMessageHandler(nil)
    }
    let clearCookiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.clearCookies", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearCookiesChannel.setMessageHandler { _, reply in
        do {
          try api.clearCookies()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearCookiesChannel.setMessageHandler(nil)
    }
    let setCookieChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.setCookie", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setCookieChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        let keyArg = args[1] as! String
        let valueArg = args[2] as! String
        do {
          try api.setCookie(url: urlArg, key: keyArg, value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setCookieChannel.setMessageHandler(nil)
    }
    let getCookiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.getCookies", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCookiesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        api.getCookies(url: urlArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      getCookiesChannel.setMessageHandler(nil)
    }
    let httpAuthResponseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.httpAuthResponse", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      httpAuthResponseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        let requestIdArg = args[1] is Int64 ? args[1] as! Int64 : Int64(args[1] as! Int32)
        let usernameArg = args[2] as! String
        let passwordArg = args[3] as! String
        do {
          try api.httpAuthResponse(viewId: viewIdArg, requestId: requestIdArg, username: usernameArg, password: passwordArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      httpAuthResponseChannel.setMessageHandler(nil)
    }
    let cancelHttpAuthChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.cancelHttpAuth", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelHttpAuthChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        let requestIdArg = args[1] is Int64 ? args[1] as! Int64 : Int64(args[1] as! Int32)
        do {
          try api.cancelHttpAuth(viewId: viewIdArg, requestId: requestIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelHttpAuthChannel.setMessageHandler(nil)
    }
    let updateSecurityConfigChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.updateSecurityConfig", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateSecurityConfigChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        let mixedContentModeArg: Int64? = args[1] is NSNull ? nil : (args[1] is Int64? ? args[1] as! Int64? : Int64(args[1] as! Int32))
        let safeBrowsingEnabledArg: Bool? = nilOrValue(args[2])
        let zoomEnabledArg: Bool? = nilOrValue(args[3])
        do {
          try api.updateSecurityConfig(viewId: viewIdArg, mixedContentMode: mixedContentModeArg, safeBrowsingEnabled: safeBrowsingEnabledArg, zoomEnabled: zoomEnabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateSecurityConfigChannel.setMessageHandler(nil)
    }
    let evaluateJavascriptChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.evaluateJavascript", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      evaluateJavascriptChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        let javascriptArg = args[1] as! String
        do {
          try api.evaluateJavascript(viewId: viewIdArg, javascript: javascriptArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      evaluateJavascriptChannel.setMessageHandler(nil)
    }
    let runJavascriptReturningResultChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.runJavascriptReturningResult", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      runJavascriptReturningResultChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        let javascriptArg = args[1] as! String
        api.runJavascriptReturningResult(viewId: viewIdArg, javascript: javascriptArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      runJavascriptReturningResultChannel.setMessageHandler(nil)
    }
    let postBridgeMessageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.postBridgeMessage", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      postBridgeMessageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        let messageArg = args[1] as! String
        do {
          try api.postBridgeMessage(viewId: viewIdArg, message: messageArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      postBridgeMessageChannel.setMessageHandler(nil)
    }
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fixit_webview.FixitWebViewHostApi.dispose", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        do {
          try api.dispose(viewId: viewIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
  }
}
